# Generated by Django 2.2.7 on 2019-12-02 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 2, 15, 10, 36, 4575), verbose_name='date published'),
        ),
    ]
